import Image from "next/image";
import Link from "next/link";

export const metadata: Metadata = {
    title: "About OPN.MY - Free URL Shortner",
    description: "About - Free URL Shortner",
};

export default function About(){
    return (
        <main className="mainContent">
            <section id="aboutFirst" className="py-5">
                <div className="container">
                    <div className="row align-items-center">
                        <div className="col-lg-12">
                            <h2>About Us</h2>
                            <p><Link href="/">OPN.MY</Link> is a powerful and easy-to-use web tool crafted to help users create short links and QR codes for any URL. In today’s digital world, sharing links in a concise, accessible way is essential, whether it’s for personal use, marketing, or business purposes. OPN.MY provides an efficient solution by converting long, complex URLs into short, manageable links and QR codes that can be shared effortlessly across various platforms, including social media, emails, and print materials.</p>
                            <p>By creating shortened links, you not only save space but also make your content more visually appealing, which can improve user engagement and click-through rates. Additionally, QR codes generated by OPN.MY allow users to scan and access URLs directly on their mobile devices, streamlining access to information without the hassle of typing in long web addresses. This makes OPN.MY an ideal tool for businesses looking to improve their marketing efforts or individuals wanting a seamless way to share content with friends, family, or followers.</p>
                            <p>Beyond link and QR code generation, OPN.MY also provides basic analytics, enabling users to track the performance of their shared links. This feature is especially useful for businesses, marketers, and content creators who want to understand their audience’s engagement and optimize their strategies based on real-time data.</p>
                            <p>If you have any questions, technical issues, or feedback, our dedicated support team is here to assist you. We understand the importance of quick and reliable assistance, so feel free to reach out to us at <Link href="mailto:contact@opn.my">contact@opn.my</Link> for inquiries related to the website, advertisements, or general help.</p> 
                            <p>At OPN.MY, our mission is to make URL management simple, effective, and accessible for everyone, so you can focus on sharing valuable content without the hassle of long links or complex QR generation tools.</p>
                        </div>
                        <div className="col-lg-12">
                            <h2 className="mt-5 mb-3">Creator Story</h2>
                        </div>
                        <div className="col-lg-4">
                            <Image 
                                src="/Creator-rajat.jpeg"
                                width={400}
                                height={300}
                                alt="Rajat Kumar"
                            />
                        </div>
                        <div className="col-lg-8">
                            <p className="fs-4">
                                <em>“Hey! 👋🏼 My name is Rajat Kumar and I am a software developer based in India. I enjoy solving problems using computer programming and I love making things online free to use for community.” ~ Rajat</em>
                            </p>
                            <p>That’s why I created FreeURL Shortener—an easy-to-use platform where you can create short links, generate QR codes, and track clicks completely free. You can also create unlimited links without any restrictions, making it ideal for businesses, creators, or anyone looking to share links efficiently.</p>
                            <p>The idea came from my belief that online tools should be simple, effective, and accessible to everyone. FreeURL Shortener reflects this mission, offering special features like built-in QR code generation and free tracking, allowing you to monitor your links and gain insights without any cost.</p>
                        </div>
                    </div>
                </div>
            </section>
        </main>
    );
}